#!/usr/bin/env ruby
require 'pathname' #detecting the correct path of a file even if its a symlink
require File.dirname(Pathname.new(__FILE__).realpath) + "/lib/fresnel"

COLOR=false
CACHE=true
CACHE_TIMEOUT=500.seconds
TERM_SIZE=80

Signal.trap("SIGINT") { 
  puts "Stopping..."
  exit(0) 
}

fresnel=Fresnel.new(:cache=>CACHE, :cache_timeout=>CACHE_TIMEOUT)

case ARGV[0]
  when "projects"
    fresnel.projects
  when "tickets"
    fresnel.tickets
  when "bins"
    fresnel.get_bins
  when "create"
    fresnel.create
  when /\d+/
    if ARGV[1]
      case ARGV[1]
        when "comment"
          fresnel.comment(ARGV[0])
        when /^(open|closed?|hold|resolved|invalid)$/
          fresnel.change_state(:ticket=>ARGV[0],:state=>ARGV[1])
        when "online"
          fresnel.open_browser_for_ticket(ARGV[0])
        when "assign"
          fresnel.assign(:ticket=>ARGV[0])
        when "claim"
          fresnel.claim(:ticket=>ARGV[0])
        else
          puts Frame.new(:header=>"Notice",:body=>"not sure what to do for #{ARGV[1]}")
      end
    else
      fresnel.show_ticket(ARGV[0])
    end
  else
    fresnel.tickets
    #puts Frame.new(:header=>"Notice",:body=>"not sure what to do for #{ARGV[0]}")
end

